// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Executive Member documents */
interface ExecutivememberDocumentData {
    /**
     * MemberFullName field in *Executive Member*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: executivemember.memberfullname
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    memberfullname: prismicT.KeyTextField;
    /**
     * MemberFirstName field in *Executive Member*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: executivemember.memberfirstname
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    memberfirstname: prismicT.KeyTextField;
    /**
     * MemberLastName field in *Executive Member*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: executivemember.memberlastname
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    memberlastname: prismicT.KeyTextField;
    /**
     * MemberLink field in *Executive Member*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: executivemember.memberlink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    memberlink: prismicT.LinkField;
    /**
     * MemberProfileImage field in *Executive Member*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: executivemember.memberprofileimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    memberprofileimage: prismicT.ImageField<never>;
}
/**
 * Executive Member document from Prismic
 *
 * - **API ID**: `executivemember`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExecutivememberDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ExecutivememberDocumentData>, "executivemember", Lang>;
/** Content for Executive Role documents */
interface ExecutiveroleDocumentData {
    /**
     * RoleTitle field in *Executive Role*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: executiverole.roletitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    roletitle: prismicT.KeyTextField;
    /**
     * RoleNickname field in *Executive Role*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: executiverole.rolenickname
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    rolenickname: prismicT.KeyTextField;
    /**
     * RoleDescription field in *Executive Role*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Describe role and responsibilities
     * - **API ID Path**: executiverole.roledescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    roledescription: prismicT.RichTextField;
}
/**
 * Executive Role document from Prismic
 *
 * - **API ID**: `executiverole`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExecutiveroleDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ExecutiveroleDocumentData>, "executiverole", Lang>;
/** Content for Executive Team documents */
interface ExecutiveteamDocumentData {
    /**
     * ExecutiveTeamTitle field in *Executive Team*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: executiveteam.executiveteamtitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    executiveteamtitle: prismicT.KeyTextField;
    /**
     * ExecutiveTeamCurrent field in *Executive Team*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: executiveteam.executiveteamcurrent
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    executiveteamcurrent: prismicT.BooleanField;
    /**
     * ExecutiveTeamMembers field in *Executive Team*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: executiveteam.executiveteammembers[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    executiveteammembers: prismicT.GroupField<Simplify<ExecutiveteamDocumentDataExecutiveteammembersItem>>;
}
/**
 * Item in Executive Team → ExecutiveTeamMembers
 *
 */
export interface ExecutiveteamDocumentDataExecutiveteammembersItem {
    /**
     * ExecutiveMember field in *Executive Team → ExecutiveTeamMembers*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: executiveteam.executiveteammembers[].executivemember
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    executivemember: prismicT.RelationField<"executivemember">;
    /**
     * ExecutiveRole field in *Executive Team → ExecutiveTeamMembers*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: executiveteam.executiveteammembers[].executiverole
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    executiverole: prismicT.RelationField<"executiverole">;
}
/**
 * Executive Team document from Prismic
 *
 * - **API ID**: `executiveteam`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExecutiveteamDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ExecutiveteamDocumentData>, "executiveteam", Lang>;
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * FooterButtons field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footerbuttons[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    footerbuttons: prismicT.GroupField<Simplify<FooterDocumentDataFooterbuttonsItem>>;
    /**
     * FooterTextMenu field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footertextmenu[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    footertextmenu: prismicT.GroupField<Simplify<FooterDocumentDataFootertextmenuItem>>;
    /**
     * FooterIconMenu field in *Footer*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footericonmenu[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    footericonmenu: prismicT.GroupField<Simplify<FooterDocumentDataFootericonmenuItem>>;
}
/**
 * Item in Footer → FooterButtons
 *
 */
export interface FooterDocumentDataFooterbuttonsItem {
    /**
     * ButtonText field in *Footer → FooterButtons*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footerbuttons[].buttontext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    buttontext: prismicT.KeyTextField;
    /**
     * ButtonLink field in *Footer → FooterButtons*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footerbuttons[].buttonlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    buttonlink: prismicT.LinkField;
    /**
     * ButtonColor field in *Footer → FooterButtons*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footerbuttons[].buttoncolor
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    buttoncolor: prismicT.SelectField<"Blue" | "Gray">;
}
/**
 * Item in Footer → FooterTextMenu
 *
 */
export interface FooterDocumentDataFootertextmenuItem {
    /**
     * LinkText field in *Footer → FooterTextMenu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footertextmenu[].linktext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    linktext: prismicT.KeyTextField;
    /**
     * linkurl field in *Footer → FooterTextMenu*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footertextmenu[].linkurl
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    linkurl: prismicT.LinkField;
}
/**
 * Item in Footer → FooterIconMenu
 *
 */
export interface FooterDocumentDataFootericonmenuItem {
    /**
     * FooterIcon field in *Footer → FooterIconMenu*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footericonmenu[].footericon
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    footericon: prismicT.SelectField<"Twitter" | "Envelope">;
    /**
     * iconlink field in *Footer → FooterIconMenu*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footericonmenu[].iconlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    iconlink: prismicT.LinkField;
    /**
     * ScreenReaderText field in *Footer → FooterIconMenu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.footericonmenu[].screenreadertext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    screenreadertext: prismicT.KeyTextField;
}
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Homepage Title field in *Homepage*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.homepagetitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    homepagetitle: prismicT.TitleField;
    /**
     * Homepage Meta Image field in *Homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.homepagemetaimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    homepagemetaimage: prismicT.ImageField<never>;
    /**
     * Homepage Meta Description field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Describe the homepage content
     * - **API ID Path**: homepage.homepagemetadescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    homepagemetadescription: prismicT.KeyTextField;
    /**
     * Homepage Twitter Image field in *Homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.homepagetwitterimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    homepagetwitterimage: prismicT.ImageField<never>;
    /**
     * Homepage Canonical URL field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Enter the canonical url
     * - **API ID Path**: homepage.homepagecanonicalurl
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    homepagecanonicalurl: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = HeroSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Main Menu documents */
interface MainmenuDocumentData {
    /**
     * MenuItems field in *Main Menu*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: mainmenu.menuitems[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    menuitems: prismicT.GroupField<Simplify<MainmenuDocumentDataMenuitemsItem>>;
}
/**
 * Item in Main Menu → MenuItems
 *
 */
export interface MainmenuDocumentDataMenuitemsItem {
    /**
     * Item Text field in *Main Menu → MenuItems*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: mainmenu.menuitems[].itemtext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    itemtext: prismicT.KeyTextField;
    /**
     * Item Link field in *Main Menu → MenuItems*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: mainmenu.menuitems[].itemlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    itemlink: prismicT.LinkField;
    /**
     * itemicon field in *Main Menu → MenuItems*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: mainmenu.menuitems[].itemicon
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    itemicon: prismicT.SelectField<"AcademicCap" | "Calendar" | "ChatAlt2" | "Cloud" | "Identification" | "Link" | "Newspaper" | "Sun" | "Home" | "Plus">;
}
/**
 * Main Menu document from Prismic
 *
 * - **API ID**: `mainmenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainmenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MainmenuDocumentData>, "mainmenu", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Icon field in *Page*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: page.icon
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    icon: prismicT.SelectField<"1" | "2">;
    /**
     * MetaImage field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.metaimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    metaimage: prismicT.ImageField<never>;
    /**
     * TwitterImage field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.twitterimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    twitterimage: prismicT.ImageField<never>;
    /**
     * MetaDescription field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.metadescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    metadescription: prismicT.KeyTextField;
    /**
     * CanonicalUrl field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.canonicalurl
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    canonicalurl: prismicT.KeyTextField;
}
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Site Metadata documents */
interface SitemetadataDocumentData {
    /**
     * Site Title field in *Site Metadata*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Site Title
     * - **API ID Path**: sitemetadata.sitetitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    sitetitle: prismicT.TitleField;
    /**
     * Site Description field in *Site Metadata*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Describe the site
     * - **API ID Path**: sitemetadata.sitedescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    sitedescription: prismicT.KeyTextField;
    /**
     * Site Meta Image field in *Site Metadata*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: sitemetadata.sitemetaimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    sitemetaimage: prismicT.ImageField<never>;
    /**
     * Site Twitter Image field in *Site Metadata*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: sitemetadata.sitetwitterimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    sitetwitterimage: prismicT.ImageField<never>;
    /**
     * Site Logo field in *Site Metadata*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: sitemetadata.sitelogo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    sitelogo: prismicT.ImageField<never>;
    /**
     * Address field in *Site Metadata*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sitemetadata.address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    address: prismicT.RichTextField;
    /**
     * Tax ID field in *Site Metadata*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: sitemetadata.taxid
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    taxid: prismicT.KeyTextField;
}
/**
 * Site Metadata document from Prismic
 *
 * - **API ID**: `sitemetadata`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SitemetadataDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SitemetadataDocumentData>, "sitemetadata", Lang>;
export type AllDocumentTypes = ExecutivememberDocument | ExecutiveroleDocument | ExecutiveteamDocument | FooterDocument | HomepageDocument | MainmenuDocument | PageDocument | SitemetadataDocument;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * Hero Title field in *Hero → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Enter Hero Title
     * - **API ID Path**: hero.primary.herotitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    herotitle: prismicT.TitleField;
    /**
     * HeroBackgroundImage field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.herobackgroundimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    herobackgroundimage: prismicT.ImageField<never>;
    /**
     * HeroHeadline field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Enter hero headline text
     * - **API ID Path**: hero.primary.heroheadline
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heroheadline: prismicT.KeyTextField;
    /**
     * Hero Headline Span field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: This text will be colored
     * - **API ID Path**: hero.primary.heroheadlinespan
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heroheadlinespan: prismicT.KeyTextField;
    /**
     * Hero Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.herodescription
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    herodescription: prismicT.RichTextField;
    /**
     * Hero Call To Action field in *Hero → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Enter call to action
     * - **API ID Path**: hero.primary.herocta
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    herocta: prismicT.TitleField;
    /**
     * Hero CTA Description field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Describe the CTA
     * - **API ID Path**: hero.primary.heroctadescription
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heroctadescription: prismicT.RichTextField;
}
/**
 * Item in Hero → Items
 *
 */
export interface HeroSliceDefaultItem {
    /**
     * ButtonText field in *Hero → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.items[].buttontext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    buttontext: prismicT.KeyTextField;
    /**
     * ButtonLink field in *Hero → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.items[].buttonlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    buttonlink: prismicT.LinkField;
    /**
     * ButtonColor field in *Hero → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select button color
     * - **Default Value**: Blue
     * - **API ID Path**: hero.items[].buttoncolor
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    buttoncolor: prismicT.SelectField<"Blue" | "Gray", "filled">;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, Simplify<HeroSliceDefaultItem>>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ExecutivememberDocumentData, ExecutivememberDocument, ExecutiveroleDocumentData, ExecutiveroleDocument, ExecutiveteamDocumentData, ExecutiveteamDocumentDataExecutiveteammembersItem, ExecutiveteamDocument, FooterDocumentData, FooterDocumentDataFooterbuttonsItem, FooterDocumentDataFootertextmenuItem, FooterDocumentDataFootericonmenuItem, FooterDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, MainmenuDocumentData, MainmenuDocumentDataMenuitemsItem, MainmenuDocument, PageDocumentData, PageDocument, SitemetadataDocumentData, SitemetadataDocument, AllDocumentTypes, HeroSliceDefaultPrimary, HeroSliceDefaultItem, HeroSliceDefault, HeroSliceVariation, HeroSlice };
    }
}
