// Code generated by Slice Machine. DO NOT EDIT.

import DefinitionList from './DefinitionList';
import ExecutiveTeam from './ExecutiveTeam';
import Hero from './Hero';
import Prose from './Prose';
import TextWithImage from './TextWithImage';

export {
	DefinitionList,
	ExecutiveTeam,
	Hero,
	Prose,
	TextWithImage,
};

export const components = {
	definition_list: DefinitionList,
	executive_team: ExecutiveTeam,
	hero: Hero,
	prose: Prose,
	text_with_image: TextWithImage,
};
