// Code generated by Slice Machine. DO NOT EDIT.

import ExecutiveTeam from './ExecutiveTeam';
import Hero from './Hero';
import Prose from './Prose';

export {
	ExecutiveTeam,
	Hero,
	Prose,
};

export const components = {
	executive_team: ExecutiveTeam,
	hero: Hero,
	prose: Prose,
};
